# Docker Compose for WordPress with Data Persistence & phpMyAdmin
#
version: "2"
services:
  my-wpdb:
    image: mysql:5.7
    volumes:
      - ./wp-data:/var/lib/mysql
    ports:
      - "8082:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  my-wp:
    image: wordpress
    volumes:
      - ./wp-app:/var/www/html
    ports:
      - "8080:80"
    links:
      - my-wpdb:mysql
    environment:
      WORDPRESS_DB_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    links:
      - my-wpdb:db
    ports:
      - "8081:80"
    volumes:
      - /sessions

volumes:
  wp-data:
  wp-app:
